version: "3.3"

services:
  fpm:
    build:
      context: .
      dockerfile: Docker/Fpm.Dockerfile
    volumes:
      - /var/www/TontiLagunaPrime/:/var/www/app
    ports:
      - 127.0.0.1:9000:9000
    networks:
      - internal

networks:
  internal:
    driver: bridge